/**
 * Dicionário Global de Códigos de Erro
 * Esse Enum é o "idioma único" entre o Backend e o Frontend.
 * Todas as mensagens de erro do sistema devem estar mapeadas aqui.
 */
export enum ErrorCodes {
  // --- Autenticação ---
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHENTICATED = 'UNAUTHENTICATED',

  // --- Usuário e Cadastro ---
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',

  // --- Validação e Entrada ---
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  FIELD_VALIDATION = 'FIELD_VALIDATION',
  INVALID_JSON_FORMAT = 'INVALID_JSON_FORMAT',
  EMPTY_PAYLOAD = 'EMPTY_PAYLOAD',
  INVALID_CONTENT_TYPE = 'INVALID_CONTENT_TYPE',
  INVALID_JSON_STRUCTURE = 'INVALID_JSON_STRUCTURE',

  // --- Infraestrutura e Sistema ---
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  CLEANUP_JOB_FAILED = 'CLEANUP_JOB_FAILED',
  
  // --- Serviços Externos ---
  EMAIL_SERVICE_UNAVAILABLE = 'EMAIL_SERVICE_UNAVAILABLE',
  DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED'
}
